### PR TITLE
Major Changes to Node CI

### PR DESCRIPTION
**Pull request by R4356th**
Major changes to Node CI:

- Rewrote the whole check
- There are now separate commands for linting CSS, JS and just format (i.e. Prettier) which all run on ``npm test``
- ``npm fix`` also fixes Stylelint errors now
- Added ESLint for linting all JavaScript and Vue
- Checks now run on Node version 14.x instead of 12.x

### CODE REVIEW

**Comment by R4356th** [comment]
The PHP CI failures are unrelated and Node.JS CI needs @GrahamSH-LLK's help to make sure detected issues are automatically fixed.

**Comment by R4356th** [comment]
> 
> 
> make sure detected issues are automatically fixed.

Never mind that part. It is working it seems. The only issue is that Prettier is conflicting with ESLint.

**Comment by GrahamSH-LLK** [comment]
There's a prettier config for eslint

**Comment by R4356th** [comment]
> 
> 
> There's a prettier config for eslint

Well, in that case, could you please add it or point me to its docs?

**Comment by R4356th** [comment]
I found it myself actually.

**Comment by R4356th** [comment]
The auto commit action still thinks there is nothing to commit despite there being Prettier fixes.

**Comment by R4356th** [comment]
This needs to be redone.

**Pull request closed without merging**
